- repo: https://github.com/YLoveX/AutoFormatTest.git
  rev: "master"
  hooks:
    - id: flutter-format
      files: lib/* # Only format source files
      # exclude: lib/src/avatar.dart # Exclude the avatar widget