- repo: https://github.com/Cretezy/dart-format-pre-commit
  rev: "master"
  hooks:
    - id: dart-format
      files: lib/* # Only format source files
      # exclude: lib/src/utils.dart # Exclude utils